print( "please type your name in : " )
my_name = input()
print( " Nice to meet you ", my_name )
print( "So ", my_name , "What is your favorite food?" )
favorite_food = input()
print( "ah favorite food is ", favorite_food )
print("So,", my_name,  "Where do you live?")
your_place = input()
print("I see you live in" , your_place , "It was a great place to visit! " )
print("How Old are you?")
your_age = input()
print(" oh! your " , your_age ,  "but you look so young!" )
print("What is your habbit?")
my_habbit = input()
print("Okay! Nice to meet you!")
print("Have a Great Day")

